services:
  - type: web
    name: delhivery-network-intelligence
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run dashboard/app.py --server.port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
